---
- name: Copy schema files
  copy:
    src: "{{ item }}"
    dest: "/etc/dirsrv/slapd-{{ dirsrv_serverid }}/schema"
    mode: '440'  # 99user.ldif is 660, but these ones should be read only
    seuser: unconfined_u  # Same as 99user.ldif
    owner: dirsrv
    group: dirsrv
  loop: "{{ dirsrv_custom_schema }}"
  notify: dirsrv schema reload

- name: Search other schema files
  find:
    paths: "/etc/dirsrv/slapd-{{ dirsrv_serverid }}/schema"
    file_type: file
    # https://stackoverflow.com/a/53758369
    excludes: "{{ dirsrv_custom_schema | map('basename') | list + ['99user.ldif'] }}"
  notify: dirsrv schema reload

- name: Delete other schema files
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ dirsrv_found_files['files'] }}"
  notify: dirsrv schema reload
