---
- name: Enable plugins
  ldap_attr:
    server_uri: "ldap://localhost"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn={{ item.key }},cn=plugins,cn=config"
    name: nsslapd-pluginEnabled
    values: "{{ 'on' if item.value else 'off' }}"
    state: exact
  loop: "{{ dirsrv_plugins_enabled | dict2items }}"

- name: Remove DNA plugin configuration (if disabled)
  ldap_entry:
    server_uri: "ldap://localhost"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "{{ item }}"
    state: absent
  loop:
    - "cn=UID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
    - "cn=GID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
  when: "'Distributed Numeric Assignment Plugin' in dirsrv_plugins_enabled and not dirsrv_plugins_enabled['Distributed Numeric Assignment Plugin']"
  notify: dirsrv restart

- name: Create DNA plugin configuration (if enabled)
  ldap_entry:
    server_uri: "ldap://localhost"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "{{ item }}"
    objectClass:
      - top
      - extensibleObject
    state: present
  loop:
    - "cn=UID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
    - "cn=GID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
  when: "'Distributed Numeric Assignment Plugin' in dirsrv_plugins_enabled and dirsrv_plugins_enabled['Distributed Numeric Assignment Plugin']"
  notify: dirsrv restart

- name: Configure DNA plugin parameters (UID)
  ldap_attr:
    server_uri: "ldap://localhost"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn=UID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: exact
  loop:
    - { name: "cn", value: "UID numbers" }
    - { name: "dnatype", value: "uidNumber" }
    - { name: "dnamagicregen", value: "magic" }  # doesn't have to be a number
    - { name: "dnafilter", value: "(objectclass=posixAccount)" }
    - { name: "dnascope", value: "{{ dirsrv_suffix }}" }
    - { name: "dnanextvalue", value: "{{ dirsrv_dna_plugin.uid_min }}" }
    - { name: "dnamaxvalue", value: "{{ dirsrv_dna_plugin.uid_max }}" }
  when: "'Distributed Numeric Assignment Plugin' in dirsrv_plugins_enabled and dirsrv_plugins_enabled['Distributed Numeric Assignment Plugin']"
  notify: dirsrv restart

- name: Configure DNA plugin parameters (GID)
  ldap_attr:
    server_uri: "ldap://localhost"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn=GID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: exact
  loop:
    - { name: "cn", value: "GID numbers" }
    - { name: "dnatype", value: "gidNumber" }
    - { name: "dnamagicregen", value: "magic" }
    - { name: "dnafilter", value: "(objectclass=posixAccount)" }
    - { name: "dnascope", value: "{{ suffix }}" }
    - { name: "dnanextvalue", value: "{{ dirsrv_dna_plugin.gid_min }}" }
    - { name: "dnamaxvalue", value: "{{ dirsrv_dna_plugin.gid_max }}" }
  when: "'Distributed Numeric Assignment Plugin' in dirsrv_plugins_enabled and dirsrv_plugins_enabled['Distributed Numeric Assignment Plugin']"
  notify: dirsrv restart
